// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUt8OvsBvffypjSGLRc0UH2LGOAl0K8Zg',
    appId: '1:963688951929:web:dd726f763ff745529c24a8',
    messagingSenderId: '963688951929',
    projectId: 'health-sync-55923',
    authDomain: 'health-sync-55923.firebaseapp.com',
    storageBucket: 'health-sync-55923.appspot.com',
    measurementId: 'G-HGKD7S86K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVDPbm38utkB7j2jU1JqP3FPjVhUBTVc4',
    appId: '1:963688951929:android:c640848ac8fb2c2f9c24a8',
    messagingSenderId: '963688951929',
    projectId: 'health-sync-55923',
    storageBucket: 'health-sync-55923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2xpT5GabMw4nHaOGppOjlMnSTMU_EYK4',
    appId: '1:963688951929:ios:b8cde1c56879bd659c24a8',
    messagingSenderId: '963688951929',
    projectId: 'health-sync-55923',
    storageBucket: 'health-sync-55923.appspot.com',
    iosBundleId: 'com.example.healthsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2xpT5GabMw4nHaOGppOjlMnSTMU_EYK4',
    appId: '1:963688951929:ios:0580b50897beed889c24a8',
    messagingSenderId: '963688951929',
    projectId: 'health-sync-55923',
    storageBucket: 'health-sync-55923.appspot.com',
    iosBundleId: 'com.example.healthsync.RunnerTests',
  );
}
